version: '3.8'

services:
  puppet:
    image: ${REGISTRY_PATH}/container-puppetserver:main-7
    hostname: puppet
    environment:
      - PUPPETSERVER_HOSTNAME=puppet
      - PUPPETSERVER_PORT=8140
      - PUPPETDB_HOSTNAME=puppetdb
      - PUPPETDB_SSL_PORT=8081
      - USE_PUPPETDB=true
      - AUTOSIGN=true
      # For private repos, use git@github.com:user/repo.git and provide SSH keys
      # - R10K_REMOTE=https://github.com/betadots/demo-control-repo.git
    volumes:
      - puppetserver:/opt/puppetlabs/server/data/puppetserver
    restart: always
    ports:
      - 8140:8140

  puppetdb:
    image: ${REGISTRY_PATH}/container-puppetdb:main-7
    hostname: puppetdb
    environment:
      - USE_PUPPETSERVER=true
      - PUPPETSERVER_HOSTNAME=puppet
      - PUPPETSERVER_PORT=8140
      - PUPPETDB_SSL_PORT=8081
      - PUPPETDB_POSTGRES_HOSTNAME=postgres
      - PUPPETDB_POSTGRES_PORT=5432
      - PUPPETDB_PASSWORD=${POSTGRES_PASSWORD:-puppetdb}
      - PUPPETDB_USER=${POSTGRES_USER:-puppetdb}
    volumes:
      - puppetdb:/opt/puppetlabs/server/data/puppetdb
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - postgres
      - puppet

  postgres:
    image: docker.io/postgres:16.1-alpine
    hostname: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-puppetdb}
      - POSTGRES_USER=${POSTGRES_USER:-puppetdb}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-puppetdb}
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - puppetdb-postgres:/var/lib/postgresql/data
    restart: always
    expose:
      - 5432

  puppetboard:
    image: ${REGISTRY_PATH}/puppetboard:latest
    hostname: puppetboard
    environment:
      - PUPPETDB_HOST=puppetdb
      - PUPPETDB_PORT=8080
      - PUPPETBOARD_PORT=8088
      - SECRET_KEY=628c4e02daaaca2b90242491f607d3704153d424f215ac51b1dd873055e102a5  # Long random String : python3 -c 'import secrets; print(secrets.token_hex())'
    restart: always
    ports:
      - 8088:8088
    depends_on:
      - puppetdb

networks:
  default:
    name: crafty-oss

volumes:
  puppetserver:
  puppetdb:
  puppetdb-postgres:
