version: '3.8'

services:
  puppet-lb:
    image: nginx:1.25.3
    ports:
      - 8140:8140
    hostname: puppet-lb
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    networks:
      - default
      - crafty-ha

networks:
  default:
    name: crafty-ha-lb
  crafty-ha:
    external: true
