---
name: "General CI 🚦🚥"

on:
  workflow_call:
    inputs:
      shellcheck_scan_dir:
        description: "Dir to scan for shell scripts."
        required: true
        default: './bin/'
        type: "string"

jobs:
  shellcheck:
    name: 'Shell Check'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Differential ShellCheck
      uses: redhat-plumbers-in-action/differential-shellcheck@v5
      with:
        scan-directory: ${{ inputs.shellcheck_scan_dir }}
